### ISSUE TITLE
Node-Red example

### ISSUE THREAD

**Issue by ezcell** [Zontex/red-alert#1]
Hi! 
My coding skills are terrible, but I'm getting there, slowly. I was wondering if someone can help me make this API into a node in Node-Red, for use in my home automation system. Anyone out there use node-red?

**Comment by Zontex** [comment]
Hi,
@samuelcardillo is the one ported the code into Node.JS he might help you.
anything regarding python - comes to me :)
Samuel, do you think you could give the guy hand in this one?

**Comment by samuelcardillo** [comment]
Hey, the Node module is already written and ready to use. The commented section on the top is displaying an example of how to. Nonetheless, I will commit few updates to it as soon as I can to fix few issues I have noticed.
